export NCCL_SOCKET_IFNAME=bond0
export NCCL_NET_PLUGIN=''
export NCCL_IB_GID_INDEX=3
export NCCL_IB_TIMEOUT=22
export NCCL_IB_RETRY_CNT=7
export NCCL_IB_SL=5
export NCCL_IB_TC=136
export NCCL_IB_HCA=mlx5_bond
export NCCL_DEBUG=INFO
export NCCL_SET_THREAD_NAME=1
export NCCL_IB_QPS_PER_CONNECTION=8
export NCCL_SET_THREAD_NAME=1
export NCCL_DEBUG_SUBSYS=INIT,TUNING,GRAPH
export NCCL_RUNTIME_CONNECT=0


export NVSHMEM_DEBUG=INFO
export NVSHMEM_DEBUG_SUBSYS=INIT
export NVSHMEM_IBRC_ROCE_LAG_PORT_SELECTION=3  
export NVSHMEM_IB_GID_INDEX=3
export NVSHMEM_IB_TRAFFIC_CLASS=16
export NVSHMEM_IB_SL=5
export NVSHMEM_ENABLE_NIC_PE_MAPPING=1
export NVSHMEM_HCA_PE_MAPPING="mlx5_bond_0:1:2,mlx5_bond_1:1:2,mlx5_bond_2:1:2,mlx5_bond_3:1:2"


export GLOO_SOCKET_IFNAME=eth0

export ACCL_DISPATCH_NUM_WARP_GROUPS=4
export ACCL_COMBINE_NUM_WARP_GROUPS=4

export PD_SCHEDULER_ROUND_ROBIN=1

#LD_LIBRARY_PATH=/opt/gdrcopy/lib /opt/gdrcopy/bin/gdrcopy_copybw


