FROM reg.docker.alibaba-inc.com/aii/aistudio:8900124-20250307163740

RUN tee /home/admin/docker_install.sh <<EOF

set -e

# 安装cuda12.4
curl http://dmsint.cn-hangzhou.alipay.aliyun-inc.com/noao/yuhong.gyh/cuda/cuda-12.4.tar | tar -xvf - -C /usr/local
rm -rf /usr/local/cuda
pushd /usr/local/ && ln -s cuda-12.4 cuda && popd
# 让/usr/local/cuda/compat作为软连接，可以被handle_cuda_compat.py删除掉。一般来说A卡需要compat，L卡和H卡不需要。
pushd /usr/local/cuda/ && mv compat compat_backup && ln -s compat_backup compat && popd
sed -i 's/base64\.encodestring/base64\.encodebytes/g' /opt/conda/lib/python3.10/site-packages/osscmd/oss_util.py

pip install tokenizers==0.21.1

pip uninstall -y torch torchvision torchaudio
pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 xformers==0.0.29.post2
pip install toml pytest setuptools_scm outlines_core openai==1.58.1
pip install --upgrade jinja2
find /usr -name libarchive.so.13 || echo "OK"
rpm --rebuilddb && yum install -y libarchive
find /usr -name libarchive.so.13
rpm --rebuilddb && yum install -y gcc glibc-devel libcap-devel
pip install python-prctl

pip install decord && pip install torchao

# FlashInfer安装
pip install "https://scmcenter.cn-hangzhou.alipay.aliyun-inc.com/antcodebuild/artifacts/WK50b0331b2cd74e1c862f92040aacb331/BJ33f3b3be61fc4495a17d35c17d5357ee/2025-04-30-08-14-08/flashinfer/flashinfer_python-0.2.5-cp38-abi3-linux_x86_64.whl?Expires=1748592854&OSSAccessKeyId=bWwpuXuj5yuYKDDK&Signature=v8%2BkuY7kqq3E%2FD9WwpM7aaxdKR4%3D"

# sglang和sgl_kernel安装
wget "https://scmcenter.cn-hangzhou.alipay.aliyun-inc.com/antcodebuild/artifacts/WK50b0331b2cd74e1c862f92040aacb331/BJ0df06d446edb43c49f8240cc222e1831/2025-05-12-13-54-22/sgl_kernel/sgl_kernel-0.1.2.post1-cp39-abi3-linux_x86_64.whl?Expires=1749650064&OSSAccessKeyId=bWwpuXuj5yuYKDDK&Signature=8M3cbYX7TJY%2FzKvXN1BdJaSwYW4%3D" -O sgl_kernel-0.1.2.post1-cp39-abi3-linux_x86_64.whl
wget "https://scmcenter.cn-hangzhou.alipay.aliyun-inc.com/antcodebuild/artifacts/WK50b0331b2cd74e1c862f92040aacb331/BJ0df06d446edb43c49f8240cc222e1831/2025-05-12-13-54-22/sglang/sglang-0.4.6.post3-py3-none-any.whl?Expires=1749650062&OSSAccessKeyId=bWwpuXuj5yuYKDDK&Signature=NU307kljq6P6Hja%2BWmqfJSgr%2Fwc%3D" -O sglang-0.4.6.post3-py3-none-any.whl
pip install sgl_kernel-0.1.2.post1-cp39-abi3-linux_x86_64.whl
pip install sglang-0.4.6.post3-py3-none-any.whl[all]

#torch compile缓存
wget "http://dmsint.cn-hangzhou.alipay.aliyun-inc.com/aistudio/temp/20250513/59fe566c0f7b41f6/inductor_root_cache.tar" -O inductor_root_cache.tar
tar -xf inductor_root_cache.tar -C /home/admin/
rm -rf inductor_root_cache.tar

# 删除maya文件
rm -rf /home/admin/maya_bin_cpu/
rm -rf /home/admin/maya_bin_gpu/

# 安装InfiniBand
rpmdb -vv --rebuilddb && yum install -y libnl3-devel
wget -q http://dmsint.cn-hangzhou.alipay.aliyun-inc.com/aistudio%2Fgpu%2Frdma-a100.tgz -O /tmp/rdma-a100.tgz
tar -xvf /tmp/rdma-a100.tgz -C /tmp
rpm -Uvh /tmp/rdma-a100/nic-libs-mellanox-rdma-5.2-2.x86_64.rpm
rm -rf /tmp/rdma-a100.tgz /tmp/rdma-a100/

# 处理不同卡需要不同的compat的情况。
wget http://dmsint.cn-hangzhou.alipay.aliyun-inc.com/noao/vllm/handle_cuda_compat.py -O /home/admin/handle_cuda_compat.py
echo "/opt/conda/bin/python /home/admin/handle_cuda_compat.py" >> /etc/bashrc

EOF

RUN cat /home/admin/docker_install.sh && bash /home/admin/docker_install.sh
CMD ["/bin/bash"]
